# Generated by Django 2.1.1 on 2018-12-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='sign',
            field=models.BooleanField(default=False, verbose_name='签到'),
        ),
    ]
