# Generated by Django 2.1.1 on 2018-12-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0004_auto_20181216_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='sign_2',
            new_name='sign',
        ),
    ]
